[build]
  publish = "."   # your site root (where index.html lives)
  command = "echo \"window._env_={SUPABASE_URL:'$SUPABASE_URL',SUPABASE_ANON_KEY:'$SUPABASE_ANON_KEY'}\" > env.js"
  # If you adopt a generator later (e.g., Eleventy/Astro), set your build command here.

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

[[plugins]]
  package = "netlify-plugin-inline-env"

  [plugins.inputs]
  keys = ["SUPABASE_URL", "SUPABASE_ANON_KEY"]

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
