backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "category", label: "Category", widget: "select", options: ["Maintenance","Painting","Fibreglass","Budget","Safety","DIY"] }
      - { name: "tags", label: "Tags", widget: "list", default: [] }
      - { name: "excerpt", label: "Excerpt", widget: "text" }
      - { name: "body", label: "Body", widget: "markdown" }
